config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path("", include("core.urls"), name="core"),
    path("rooms/", include("rooms.urls"), name="rooms"),
    path("users/", include("users.urls"), name="users"),
    path("reservations/", include("reservations.urls"), name="users"),
    path("reviews/", include("reviews.urls"), name="reviews"),
    path("lists/", include("lists.urls"), name="lists"),
    path("conversations/", include("conversation.urls"), name="conversations"),
    path("admin/", admin.site.urls),
    path("sentry-debug/", trigger_error),
]

# 1번째 인자는 File_URL 2번쨰 인자는 File 저장 폴더
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conversation/urls.py
from django.urls import path
from . import views

app_name = "conversations"

urlpatterns = [
    path("go/<int:a_pk>/<int:b_pk>/", views.go_conversation, name="go"),
    path(
        "<int:pk>/<int:host_pk>/", views.ConversationDetailView.as_view(), name="detail"
    ),
]

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

reservations/urls.py
from django.urls import path
from . import views

app_name = "reservations"

urlpatterns = [
    path(
        "create/<int:room>/<int:year>-<int:month>-<int:day>/",
        views.create,
        name="create",
    ),
    path("<int:pk>/", views.ReservationDetailView.as_view(), name="detail"),
    path("<int:pk>/<str:verb>/", views.edit_reservation, name="edit"),
    path("check/", views.ReservationCheck.as_view(), name="check"),
]

reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [path("create/<int:room>/", views.create_review, name="create")]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

# https://docs.djangoproject.com/en/3.0/topics/http/urls/

urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photo/", views.RoomPhotoView.as_view(), name="photos"),
    path("<int:pk>/photo/add", views.AddPhotoView.as_view(), name="add_photo"),
    path(
        "<int:room_pk>/photo/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete_photo",
    ),
    path(
        "<int:room_pk>/photo/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit_photo",
    ),
    path("search/", views.SearchView.as_view(), name="search"),
]

reservations/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib import messages
from core import models as core_models
from django.utils.translation import gettext_lazy as _


class BookedDay(core_models.TimeStampdModel):

    day = models.DateField()
    reservation = models.ForeignKey("Reservation", on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Booked Day"
        verbose_name_plural = "Booked Days"

    def __str__(self):
        return str(self.day)


class Reservation(core_models.TimeStampdModel):

    """ Reservation Model Definition (예약)"""

    STATUS_PENDING = "pending"
    STATUS_CONFIRMED = "confirmed"
    STATUS_CANCELED = "canceled"

    STATUS_CHOICES = (
        (STATUS_PENDING, "Pending(미결)"),
        (STATUS_CONFIRMED, "Confirmed(확인)"),
        (STATUS_CANCELED, "Canceled(취소)"),
    )

    status = models.CharField(
        max_length=12, choices=STATUS_CHOICES, default=STATUS_PENDING
    )
    check_in = models.DateField()
    check_out = models.DateField()
    guest = models.ForeignKey(
        "users.User", related_name="reservation", on_delete=models.CASCADE
    )
    room = models.ForeignKey(
        "rooms.Room", related_name="reservation", on_delete=models.CASCADE
    )

    def __str__(self):
        return f"{self.room} - {self.check_in}"

    def in_progress(self):
        now = timezone.now().date()
        return now >= self.check_in and now <= self.check_out

    in_progress.boolean = True

    def is_finished(self):
        now = timezone.now().date()
        is_finished = now > self.check_out
        if is_finished and self.status == "canceled":
            self.delete()
        return is_finished

    is_finished.boolean = True

    def save(self, *args, **kwargs):
        if True:  # 새로운 Reservation 일 경우
            start = self.check_in
            end = self.check_out
            difference = end - start
            existing_booked_day = BookedDay.objects.filter(
                day__range=(start, end), reservation__room=self.room
            ).exists()
            if not existing_booked_day:
                super().save(*args, **kwargs)
                for i in range(difference.days + 1):
                    day = start + datetime.timedelta(days=i)
                    BookedDay.objects.create(day=day, reservation=self)
                return
        return super().save(*args, **kwargs)

reservations/views.py
import datetime
from django.http import Http404
from django.views.generic import View, TemplateView
from django.contrib import messages
from django.shortcuts import render, redirect, reverse
from rooms import models as room_models
from reviews import forms as review_forms
from . import models


class CreateError(Exception):
    pass


def create(request, room, year, month, day):
    try:
        date_obj = datetime.datetime(year, month, day)
        room = room_models.Room.objects.get(pk=room)
        models.BookedDay.objects.get(day=date_obj, reservation__room=room)
        raise CreateError()
    except (room_models.Room.DoesNotExist, CreateError):
        messages.error(request, "Can't Reserve That Room")
        return redirect(reverse("core:home"))
    except models.BookedDay.DoesNotExist:
        reservation = models.Reservation.objects.create(
            guest=request.user,
            room=room,
            check_in=date_obj,
            check_out=date_obj + datetime.timedelta(days=1),
        )
        return redirect(reverse("reservations:detail", kwargs={"pk": reservation.pk}))


class ReservationDetailView(View):
    def get(self, *args, **kwargs):
        pk = kwargs.get("pk")
        reservation = models.Reservation.objects.get_or_none(pk=pk)
        if not reservation or (
            reservation.guest != self.request.user
            and reservation.room.host != self.request.user
        ):
            raise Http404()
        form = review_forms.CreateReviewForm()
        return render(
            self.request,
            "reservations/detail.html",
            {"reservation": reservation, "form": form},
        )


def edit_reservation(request, pk, verb):
    reservation = models.Reservation.objects.get_or_none(pk=pk)
    if not reservation or (
        reservation.guest != request.user and reservation.room.host != request.user
    ):
        raise Http404()
    if verb == "confirm":
        reservation.status = models.Reservation.STATUS_CONFIRMED
    elif verb == "pending":
        reservation.status = models.Reservation.STATUS_PENDING
    elif verb == "cancel":
        reservation.status = models.Reservation.STATUS_CANCELED
        reservation.delete()
    reservation.save()
    messages.success(request, "Reservation Updated")
    return redirect(reverse("reservations:detail", kwargs={"pk": reservation.pk}))


class ReservationCheck(View):
    def get(self, *args, **kwargs):
        reservations = models.Reservation.objects.filter(room__host=self.request.user)
        return render(
            self.request, "reservations/check.html", {"reservations": reservations}
        )

    def post(self, *args, **kwargs):
        reservations = models.Reservation.objects.filter(room__host=self.request.user)
        status = self.request.POST.get("reservation.pk")
        print(status)
        return redirect(reverse("reservations:check"))

templates/reservations/check.html
{% extends "base.html" %}

{% block page_title %}
    Reservation
{% endblock page_title %}

{% block serach-bar %}
{% endblock serach-bar %}

{% block content %}

    {% if reservations %}
    <div class="container mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
        <div class=" text-center pb-5 border-b w-full font-bold text-2xl"> Reservaiton </div>
        <div class="flex justify-end font-bold md:text-right w-2/3">
            <div class="mr-2">Check In</div>
            <div class="mr-20">Check Out</div>
            <div class="mr-12">Status</div>
        </div>
    {% endif %}
    {% for reservation in reservations %}
    <div class="flex self-start w-full mb-3 border-t">
        <a href = "{% url 'rooms:detail' reservation.room.pk %}" class="w-64 h-24 bg-cover bg-center rounded-lg mr-5"  style="background-image:url({{reservation.room.first_photo}})"></a>
        <div class="flex items-center w-full border-b">
            <div class="border-r pr-10 mr-10">
                <div class="w-full">{{ reservation.room.name }}</div>
                <div>Booked by : {{ reservation.guest.last_name }} </div>
            </div>
                <div class="w-1/6 flex font-medium">
                    <div>{{ reservation.check_in |date:"m-d" }} ~</div>
                    <div>{{ reservation.check_out |date:"m-d" }}</div>
                </div>
            <!-- <select id = reservation class=" w-1/3">
                <option value="?x=x"{% if reservation.status == 'pending' %} selected {% endif%}>Pendig</option>
                <option value="{{reservation}}"{% if reservation.status == 'confirmed' %} selected {% endif%}>Confirmed</option>
                <option value="{{reservation}}"{% if reservation.status == 'canceled' %} selected {% endif%}>Canceled</option>
            </select> -->
            <a href="{% url 'reservations:detail' reservation.pk %}" 
            class=" w-1/5 pl-5 mr-5 font-bold {% if reservation.status == 'pending' %} text-yellow-400
             {% elif reservation.status == 'confirmed' %} text-green-400 
             {% elif reservation.status == 'canceled' %} text-red-600 
             {% endif %}">{{ reservation.status }}</a>
        </div>
    </div>
    {% endfor %}
    
       

{% endblock content %}

templates/reservations/detail.html
{% extends "base.html" %}

{% block page_title %}
    Reservation {{ reservation.check_in }}
{% endblock page_title %}

{% block serach-bar %}
{% endblock serach-bar %}

{% block content  %}
    <div class="container mx-auto my-10 flex flex-col ">

        <div class=" border-t border-l border-r bg-cover bg-center h-56 rounded-t-lg" style="background-image: url({{reservation.room.first_photo}});"></div>
        
        <div class=" flex flex-col items-start border-l border-r border-t border-b">
            <div class=" font-medium border py-8 px-5 w-full">
                {{ reservation.check_in}} - {{reservation.check_out}} <span class=" ml-5 {% if reservation.status == 'pending' %} text-yellow-500 {% elif reservation.status == 'canceled' %} text-red-600 {% else %} text-teal-600 {% endif%}">{{reservation.get_status_display}}</span>
            </div>
    
            <span class="text-2xl border-b px-5 mt-2 w-full">
                {{ reservation.room.name }}
            </span>
            <div class="flex p-5 border-b w-full">
                <div class="flex flex-col items-center">
                    {% include "mixins/user_avatar.html" with user_obj=reservation.room.host %}
                    <span class="mt-2 text-gray-500">{{ reservation.room.host.first_name}}</span>
                </div>
                <div class=" ml-5 flex flex-col">
                    <span class="font-medium mb-px">Contact your Airbnb Host</span>
                    <a href="{% url 'conversations:go' reservation.room.host.pk reservation.guest.pk %}" class=" font-medium text-teal-500">Send a Message</a>
                </div>
            </div>
            <div class="py-10 px-5">
            {{ reservation.status}}
            {% if reservation.status != 'canceled' %}
                {% if reservation.status == 'confirmed' and reservation.is_finished %}
                    <span class=" font-bold text-2xg text-center w-full block mb-5">Write your review</span>
                    <form action="{% url 'reviews:create' reservation.room.pk %}" method="POST" class="w-1/2 m-auto">
                        {% csrf_token %}
                        {{ form }}
                        <input class="btn-link" name={{reservation.pk}}/>
                    </form>
                {% else %}
                    {% if reservation.status == '미결' %}
                        <a href="{% url 'reservations:edit' reservation.pk 'cancel' %}" class="btn-link block px-5">Cancel Reservation</a>
                    {% endif %}
                    {% if reservation.room.host == user%}
                    <div class="flex m-3">
                        <a href="{% url 'reservations:edit' reservation.pk 'confirm' %}" class="btn-link px-5 mr-6 bg-teal-600">Confirm Reservation</a>
                        <a href="{% url 'reservations:edit' reservation.pk 'cancel' %}" class="btn-link px-5 mr-6">Cancel Reservation</a>
                        <a href="{% url 'reservations:edit' reservation.pk 'pending' %}" class="btn-link px-5 bg-yellow-500">Pending Reservation</a>
                    </div>
                    {% endif %} 
                {% endif %}
            {% endif %}
            </div>
        </div>
    </div>
        

{% endblock content  %}